

export const metadata ={
  title:"Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    
      <body>

      <header
      style={{
        backgroundColor: 'black',
        padding:'2rem',
      }}>
        <p style={{color:'white'}}>Mon header</p>
      </header>

        <main>{children}</main>

        <footer
          style={{
            backgroundColor: 'red',
            padding:'2rem',
          }}
      ><p style={{color:'white'}}>Mon footer</p></footer>
      </body>
     
    </html>
  );
}
